dataconnector:
  athena:
    uri: http://data-connector-agent:8083/api/v1/athena
  mariadb:
    uri: http://data-connector-agent:8083/api/v1/mariadb
  mysql8:
    uri: http://data-connector-agent:8083/api/v1/mysql
  oracle:
    uri: http://data-connector-agent:8083/api/v1/oracle
  snowflake:
    uri: http://data-connector-agent:8083/api/v1/snowflake
